version: "3.4"

services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: express_test_db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data-express-test:rw
    ports:
      - "5432:5432"

volumes:
  db-data: {}
